# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Sanket Shah
tagline:          'Research Engineer, SMU'
# description:      ''
url:              https://sanketkshah.github.io
baseurl:          /

author:
  name:           'Sanket Shah'
  url:            https://sanketkshah.github.io/

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/sanketkshah/sanketkshah.github.io
